/**
* @module FontAwesomeService
* Contain list of font awesome icons
*
* @var data
*/

export class FontAwesomeService {
  public static data = [
    { value: '500px', label: '500px' },
    { value: 'adjust', label: 'Adjust' },
    { value: 'adn', label: 'Adn' },
    { value: 'align-center', label: 'Align Center' },
    { value: 'align-justify', label: 'Align Justify' },
    { value: 'align-left', label: 'Align Left' },
    { value: 'align-right', label: 'Align Right' },
    { value: 'amazon', label: 'Amazon' },
    { value: 'ambulance', label: 'Ambulance' },
    { value: 'anchor', label: 'Anchor' },
    { value: 'android', label: 'Android' },
    { value: 'angellist', label: 'Angellist' },
    { value: 'angle-double-down', label: 'Angle Double Down' },
    { value: 'angle-double-left', label: 'Angle Double Left' },
    { value: 'angle-double-right', label: 'Angle Double Right' },
    { value: 'angle-double-up', label: 'Angle Double Up' },
    { value: 'angle-down', label: 'Angle Down' },
    { value: 'angle-left', label: 'Angle Left' },
    { value: 'angle-right', label: 'Angle Right' },
    { value: 'angle-up', label: 'Angle Up' },
    { value: 'apple', label: 'Apple' },
    { value: 'archive', label: 'Archive' },
    { value: 'area-chart', label: 'Area Chart' },
    { value: 'arrow-circle-down', label: 'Arrow Circle Down' },
    { value: 'arrow-circle-left', label: 'Arrow Circle Left' },
    { value: 'arrow-circle-o-down', label: 'Arrow Circle O Down' },
    { value: 'arrow-circle-o-left', label: 'Arrow Circle O Left' },
    { value: 'arrow-circle-o-right', label: 'Arrow Circle O Right' },
    { value: 'arrow-circle-o-up', label: 'Arrow Circle O Up' },
    { value: 'arrow-circle-right', label: 'Arrow Circle Right' },
    { value: 'arrow-circle-up', label: 'Arrow Circle Up' },
    { value: 'arrow-down', label: 'Arrow Down' },
    { value: 'arrow-left', label: 'Arrow Left' },
    { value: 'arrow-right', label: 'Arrow Right' },
    { value: 'arrow-up', label: 'Arrow Up' },
    { value: 'arrows', label: 'Arrows' },
    { value: 'arrows-alt', label: 'Arrows Alt' },
    { value: 'arrows-h', label: 'Arrows H' },
    { value: 'arrows-v', label: 'Arrows V' },
    { value: 'asterisk', label: 'Asterisk' },
    { value: 'at', label: 'At' },
    { value: 'automobile', label: 'Automobile' },
    { value: 'backward', label: 'Backward' },
    { value: 'balance-scale', label: 'Balance Scale' },
    { value: 'ban', label: 'Ban' },
    { value: 'bank', label: 'Bank' },
    { value: 'bar-chart', label: 'Bar Chart' },
    { value: 'bar-chart-o', label: 'Bar Chart O' },
    { value: 'barcode', label: 'Barcode' },
    { value: 'bars', label: 'Bars' },
    { value: 'battery-0', label: 'Battery 0' },
    { value: 'battery-1', label: 'Battery 1' },
    { value: 'battery-2', label: 'Battery 2' },
    { value: 'battery-3', label: 'Battery 3' },
    { value: 'battery-4', label: 'Battery 4' },
    { value: 'battery-empty', label: 'Battery Empty' },
    { value: 'battery-full', label: 'Battery Full' },
    { value: 'battery-half', label: 'Battery Half' },
    { value: 'battery-quarter', label: 'Battery Quarter' },
    { value: 'battery-three-quarters', label: 'Battery Three Quarters' },
    { value: 'bed', label: 'Bed' },
    { value: 'beer', label: 'Beer' },
    { value: 'behance', label: 'Behance' },
    { value: 'behance-square', label: 'Behance Square' },
    { value: 'bell', label: 'Bell' },
    { value: 'bell-o', label: 'Bell O' },
    { value: 'bell-slash', label: 'Bell Slash' },
    { value: 'bell-slash-o', label: 'Bell Slash O' },
    { value: 'bicycle', label: 'Bicycle' },
    { value: 'binoculars', label: 'Binoculars' },
    { value: 'birthday-cake', label: 'Birthday Cake' },
    { value: 'bitbucket', label: 'Bitbucket' },
    { value: 'bitbucket-square', label: 'Bitbucket Square' },
    { value: 'bitcoin', label: 'Bitcoin' },
    { value: 'black-tie', label: 'Black Tie' },
    { value: 'bluetooth', label: 'Bluetooth' },
    { value: 'bluetooth-b', label: 'Bluetooth B' },
    { value: 'bold', label: 'Bold' },
    { value: 'bolt', label: 'Bolt' },
    { value: 'bomb', label: 'Bomb' },
    { value: 'book', label: 'Book' },
    { value: 'bookmark', label: 'Bookmark' },
    { value: 'bookmark-o', label: 'Bookmark O' },
    { value: 'briefcase', label: 'Briefcase' },
    { value: 'btc', label: 'Btc' },
    { value: 'bug', label: 'Bug' },
    { value: 'building', label: 'Building' },
    { value: 'building-o', label: 'Building O' },
    { value: 'bullhorn', label: 'Bullhorn' },
    { value: 'bullseye', label: 'Bullseye' },
    { value: 'bus', label: 'Bus' },
    { value: 'buysellads', label: 'Buysellads' },
    { value: 'cab', label: 'Cab' },
    { value: 'calculator', label: 'Calculator' },
    { value: 'calendar', label: 'Calendar' },
    { value: 'calendar-check-o', label: 'Calendar Check O' },
    { value: 'calendar-minus-o', label: 'Calendar Minus O' },
    { value: 'calendar-o', label: 'Calendar O' },
    { value: 'calendar-plus-o', label: 'Calendar Plus O' },
    { value: 'calendar-times-o', label: 'Calendar Times O' },
    { value: 'camera', label: 'Camera' },
    { value: 'camera-retro', label: 'Camera Retro' },
    { value: 'car', label: 'Car' },
    { value: 'caret-down', label: 'Caret Down' },
    { value: 'caret-left', label: 'Caret Left' },
    { value: 'caret-right', label: 'Caret Right' },
    { value: 'caret-square-o-down', label: 'Caret Square O Down' },
    { value: 'caret-square-o-left', label: 'Caret Square O Left' },
    { value: 'caret-square-o-right', label: 'Caret Square O Right' },
    { value: 'caret-square-o-up', label: 'Caret Square O Up' },
    { value: 'caret-up', label: 'Caret Up' },
    { value: 'cart-arrow-down', label: 'Cart Arrow Down' },
    { value: 'cart-plus', label: 'Cart Plus' },
    { value: 'cc', label: 'Cc' },
    { value: 'cc-amex', label: 'Cc Amex' },
    { value: 'cc-diners-club', label: 'Cc Diners Club' },
    { value: 'cc-discover', label: 'Cc Discover' },
    { value: 'cc-jcb', label: 'Cc Jcb' },
    { value: 'cc-mastercard', label: 'Cc Mastercard' },
    { value: 'cc-paypal', label: 'Cc Paypal' },
    { value: 'cc-stripe', label: 'Cc Stripe' },
    { value: 'cc-visa', label: 'Cc Visa' },
    { value: 'certificate', label: 'Certificate' },
    { value: 'chain', label: 'Chain' },
    { value: 'chain-broken', label: 'Chain Broken' },
    { value: 'check', label: 'Check' },
    { value: 'check-circle', label: 'Check Circle' },
    { value: 'check-circle-o', label: 'Check Circle O' },
    { value: 'check-square', label: 'Check Square' },
    { value: 'check-square-o', label: 'Check Square O' },
    { value: 'chevron-circle-down', label: 'Chevron Circle Down' },
    { value: 'chevron-circle-left', label: 'Chevron Circle Left' },
    { value: 'chevron-circle-right', label: 'Chevron Circle Right' },
    { value: 'chevron-circle-up', label: 'Chevron Circle Up' },
    { value: 'chevron-down', label: 'Chevron Down' },
    { value: 'chevron-left', label: 'Chevron Left' },
    { value: 'chevron-right', label: 'Chevron Right' },
    { value: 'chevron-up', label: 'Chevron Up' },
    { value: 'child', label: 'Child' },
    { value: 'chrome', label: 'Chrome' },
    { value: 'circle', label: 'Circle' },
    { value: 'circle-o', label: 'Circle O' },
    { value: 'circle-o-notch', label: 'Circle O Notch' },
    { value: 'circle-thin', label: 'Circle Thin' },
    { value: 'clipboard', label: 'Clipboard' },
    { value: 'clock-o', label: 'Clock O' },
    { value: 'clone', label: 'Clone' },
    { value: 'close', label: 'Close' },
    { value: 'cloud', label: 'Cloud' },
    { value: 'cloud-download', label: 'Cloud Download' },
    { value: 'cloud-upload', label: 'Cloud Upload' },
    { value: 'cny', label: 'Cny' },
    { value: 'code', label: 'Code' },
    { value: 'code-fork', label: 'Code Fork' },
    { value: 'codepen', label: 'Codepen' },
    { value: 'codiepie', label: 'Codiepie' },
    { value: 'coffee', label: 'Coffee' },
    { value: 'cog', label: 'Cog' },
    { value: 'cogs', label: 'Cogs' },
    { value: 'columns', label: 'Columns' },
    { value: 'comment', label: 'Comment' },
    { value: 'comment-o', label: 'Comment O' },
    { value: 'commenting', label: 'Commenting' },
    { value: 'commenting-o', label: 'Commenting O' },
    { value: 'comments', label: 'Comments' },
    { value: 'comments-o', label: 'Comments O' },
    { value: 'compass', label: 'Compass' },
    { value: 'compress', label: 'Compress' },
    { value: 'connectdevelop', label: 'Connectdevelop' },
    { value: 'contao', label: 'Contao' },
    { value: 'copy', label: 'Copy' },
    { value: 'copyright', label: 'Copyright' },
    { value: 'creative-commons', label: 'Creative Commons' },
    { value: 'credit-card', label: 'Credit Card' },
    { value: 'credit-card-alt', label: 'Credit Card Alt' },
    { value: 'crop', label: 'Crop' },
    { value: 'crosshairs', label: 'Crosshairs' },
    { value: 'css3', label: 'Css3' },
    { value: 'cube', label: 'Cube' },
    { value: 'cubes', label: 'Cubes' },
    { value: 'cut', label: 'Cut' },
    { value: 'cutlery', label: 'Cutlery' },
    { value: 'dashboard', label: 'Dashboard' },
    { value: 'dashcube', label: 'Dashcube' },
    { value: 'database', label: 'Database' },
    { value: 'dedent', label: 'Dedent' },
    { value: 'delicious', label: 'Delicious' },
    { value: 'desktop', label: 'Desktop' },
    { value: 'deviantart', label: 'Deviantart' },
    { value: 'diamond', label: 'Diamond' },
    { value: 'digg', label: 'Digg' },
    { value: 'dollar', label: 'Dollar' },
    { value: 'dot-circle-o', label: 'Dot Circle O' },
    { value: 'download', label: 'Download' },
    { value: 'dribbble', label: 'Dribbble' },
    { value: 'dropbox', label: 'Dropbox' },
    { value: 'drupal', label: 'Drupal' },
    { value: 'edge', label: 'Edge' },
    { value: 'edit', label: 'Edit' },
    { value: 'eject', label: 'Eject' },
    { value: 'ellipsis-h', label: 'Ellipsis H' },
    { value: 'ellipsis-v', label: 'Ellipsis V' },
    { value: 'empire', label: 'Empire' },
    { value: 'envelope', label: 'Envelope' },
    { value: 'envelope-o', label: 'Envelope O' },
    { value: 'envelope-square', label: 'Envelope Square' },
    { value: 'eraser', label: 'Eraser' },
    { value: 'eur', label: 'Eur' },
    { value: 'euro', label: 'Euro' },
    { value: 'exchange', label: 'Exchange' },
    { value: 'exclamation', label: 'Exclamation' },
    { value: 'exclamation-circle', label: 'Exclamation Circle' },
    { value: 'exclamation-triangle', label: 'Exclamation Triangle' },
    { value: 'expand', label: 'Expand' },
    { value: 'expeditedssl', label: 'Expeditedssl' },
    { value: 'external-link', label: 'External Link' },
    { value: 'external-link-square', label: 'External Link Square' },
    { value: 'eye', label: 'Eye' },
    { value: 'eye-slash', label: 'Eye Slash' },
    { value: 'eyedropper', label: 'Eyedropper' },
    { value: 'facebook', label: 'Facebook' },
    { value: 'facebook-f', label: 'Facebook F' },
    { value: 'facebook-official', label: 'Facebook Official' },
    { value: 'facebook-square', label: 'Facebook Square' },
    { value: 'fast-backward', label: 'Fast Backward' },
    { value: 'fast-forward', label: 'Fast Forward' },
    { value: 'fax', label: 'Fax' },
    { value: 'feed', label: 'Feed' },
    { value: 'female', label: 'Female' },
    { value: 'fighter-jet', label: 'Fighter Jet' },
    { value: 'file', label: 'File' },
    { value: 'file-archive-o', label: 'File Archive O' },
    { value: 'file-audio-o', label: 'File Audio O' },
    { value: 'file-code-o', label: 'File Code O' },
    { value: 'file-excel-o', label: 'File Excel O' },
    { value: 'file-image-o', label: 'File Image O' },
    { value: 'file-movie-o', label: 'File Movie O' },
    { value: 'file-o', label: 'File O' },
    { value: 'file-pdf-o', label: 'File Pdf O' },
    { value: 'file-photo-o', label: 'File Photo O' },
    { value: 'file-picture-o', label: 'File Picture O' },
    { value: 'file-powerpoint-o', label: 'File Powerpoint O' },
    { value: 'file-sound-o', label: 'File Sound O' },
    { value: 'file-text', label: 'File Text' },
    { value: 'file-text-o', label: 'File Text O' },
    { value: 'file-video-o', label: 'File Video O' },
    { value: 'file-word-o', label: 'File Word O' },
    { value: 'file-zip-o', label: 'File Zip O' },
    { value: 'files-o', label: 'Files O' },
    { value: 'film', label: 'Film' },
    { value: 'filter', label: 'Filter' },
    { value: 'fire', label: 'Fire' },
    { value: 'fire-extinguisher', label: 'Fire Extinguisher' },
    { value: 'firefox', label: 'Firefox' },
    { value: 'flag', label: 'Flag' },
    { value: 'flag-checkered', label: 'Flag Checkered' },
    { value: 'flag-o', label: 'Flag O' },
    { value: 'flash', label: 'Flash' },
    { value: 'flask', label: 'Flask' },
    { value: 'flickr', label: 'Flickr' },
    { value: 'floppy-o', label: 'Floppy O' },
    { value: 'folder', label: 'Folder' },
    { value: 'folder-o', label: 'Folder O' },
    { value: 'folder-open', label: 'Folder Open' },
    { value: 'folder-open-o', label: 'Folder Open O' },
    { value: 'font', label: 'Font' },
    { value: 'fonticons', label: 'Fonticons' },
    { value: 'fort-awesome', label: 'Fort Awesome' },
    { value: 'forumbee', label: 'Forumbee' },
    { value: 'forward', label: 'Forward' },
    { value: 'foursquare', label: 'Foursquare' },
    { value: 'frown-o', label: 'Frown O' },
    { value: 'futbol-o', label: 'Futbol O' },
    { value: 'gamepad', label: 'Gamepad' },
    { value: 'gavel', label: 'Gavel' },
    { value: 'gbp', label: 'Gbp' },
    { value: 'ge', label: 'Ge' },
    { value: 'gear', label: 'Gear' },
    { value: 'gears', label: 'Gears' },
    { value: 'genderless', label: 'Genderless' },
    { value: 'get-pocket', label: 'Get Pocket' },
    { value: 'gg', label: 'Gg' },
    { value: 'gg-circle', label: 'Gg Circle' },
    { value: 'gift', label: 'Gift' },
    { value: 'git', label: 'Git' },
    { value: 'git-square', label: 'Git Square' },
    { value: 'github', label: 'Github' },
    { value: 'github-alt', label: 'Github Alt' },
    { value: 'github-square', label: 'Github Square' },
    { value: 'gittip', label: 'Gittip' },
    { value: 'glass', label: 'Glass' },
    { value: 'globe', label: 'Globe' },
    { value: 'google', label: 'Google' },
    { value: 'google-plus', label: 'Google Plus' },
    { value: 'google-plus-square', label: 'Google Plus Square' },
    { value: 'google-wallet', label: 'Google Wallet' },
    { value: 'graduation-cap', label: 'Graduation Cap' },
    { value: 'gratipay', label: 'Gratipay' },
    { value: 'group', label: 'Group' },
    { value: 'h-square', label: 'H Square' },
    { value: 'hacker-news', label: 'Hacker News' },
    { value: 'hand-grab-o', label: 'Hand Grab O' },
    { value: 'hand-lizard-o', label: 'Hand Lizard O' },
    { value: 'hand-o-down', label: 'Hand O Down' },
    { value: 'hand-o-left', label: 'Hand O Left' },
    { value: 'hand-o-right', label: 'Hand O Right' },
    { value: 'hand-o-up', label: 'Hand O Up' },
    { value: 'hand-paper-o', label: 'Hand Paper O' },
    { value: 'hand-peace-o', label: 'Hand Peace O' },
    { value: 'hand-pointer-o', label: 'Hand Pointer O' },
    { value: 'hand-rock-o', label: 'Hand Rock O' },
    { value: 'hand-scissors-o', label: 'Hand Scissors O' },
    { value: 'hand-spock-o', label: 'Hand Spock O' },
    { value: 'hand-stop-o', label: 'Hand Stop O' },
    { value: 'hashtag', label: 'Hashtag' },
    { value: 'hdd-o', label: 'Hdd O' },
    { value: 'header', label: 'Header' },
    { value: 'headphones', label: 'Headphones' },
    { value: 'heart', label: 'Heart' },
    { value: 'heart-o', label: 'Heart O' },
    { value: 'heartbeat', label: 'Heartbeat' },
    { value: 'history', label: 'History' },
    { value: 'home', label: 'Home' },
    { value: 'hospital-o', label: 'Hospital O' },
    { value: 'hotel', label: 'Hotel' },
    { value: 'hourglass', label: 'Hourglass' },
    { value: 'hourglass-1', label: 'Hourglass 1' },
    { value: 'hourglass-2', label: 'Hourglass 2' },
    { value: 'hourglass-3', label: 'Hourglass 3' },
    { value: 'hourglass-end', label: 'Hourglass End' },
    { value: 'hourglass-half', label: 'Hourglass Half' },
    { value: 'hourglass-o', label: 'Hourglass O' },
    { value: 'hourglass-start', label: 'Hourglass Start' },
    { value: 'houzz', label: 'Houzz' },
    { value: 'html5', label: 'Html5' },
    { value: 'i-cursor', label: 'I Cursor' },
    { value: 'ils', label: 'Ils' },
    { value: 'image', label: 'Image' },
    { value: 'inbox', label: 'Inbox' },
    { value: 'indent', label: 'Indent' },
    { value: 'industry', label: 'Industry' },
    { value: 'info', label: 'Info' },
    { value: 'info-circle', label: 'Info Circle' },
    { value: 'inr', label: 'Inr' },
    { value: 'instagram', label: 'Instagram' },
    { value: 'institution', label: 'Institution' },
    { value: 'internet-explorer', label: 'Internet Explorer' },
    { value: 'intersex', label: 'Intersex' },
    { value: 'ioxhost', label: 'Ioxhost' },
    { value: 'italic', label: 'Italic' },
    { value: 'joomla', label: 'Joomla' },
    { value: 'jpy', label: 'Jpy' },
    { value: 'jsfiddle', label: 'Jsfiddle' },
    { value: 'key', label: 'Key' },
    { value: 'keyboard-o', label: 'Keyboard O' },
    { value: 'krw', label: 'Krw' },
    { value: 'language', label: 'Language' },
    { value: 'laptop', label: 'Laptop' },
    { value: 'lastfm', label: 'Lastfm' },
    { value: 'lastfm-square', label: 'Lastfm Square' },
    { value: 'leaf', label: 'Leaf' },
    { value: 'leanpub', label: 'Leanpub' },
    { value: 'legal', label: 'Legal' },
    { value: 'lemon-o', label: 'Lemon O' },
    { value: 'level-down', label: 'Level Down' },
    { value: 'level-up', label: 'Level Up' },
    { value: 'life-bouy', label: 'Life Bouy' },
    { value: 'life-buoy', label: 'Life Buoy' },
    { value: 'life-ring', label: 'Life Ring' },
    { value: 'life-saver', label: 'Life Saver' },
    { value: 'lightbulb-o', label: 'Lightbulb O' },
    { value: 'line-chart', label: 'Line Chart' },
    { value: 'link', label: 'Link' },
    { value: 'linkedin', label: 'Linkedin' },
    { value: 'linkedin-square', label: 'Linkedin Square' },
    { value: 'linux', label: 'Linux' },
    { value: 'list', label: 'List' },
    { value: 'list-alt', label: 'List Alt' },
    { value: 'list-ol', label: 'List Ol' },
    { value: 'list-ul', label: 'List Ul' },
    { value: 'location-arrow', label: 'Location Arrow' },
    { value: 'lock', label: 'Lock' },
    { value: 'long-arrow-down', label: 'Long Arrow Down' },
    { value: 'long-arrow-left', label: 'Long Arrow Left' },
    { value: 'long-arrow-right', label: 'Long Arrow Right' },
    { value: 'long-arrow-up', label: 'Long Arrow Up' },
    { value: 'magic', label: 'Magic' },
    { value: 'magnet', label: 'Magnet' },
    { value: 'mail-forward', label: 'Mail Forward' },
    { value: 'mail-reply', label: 'Mail Reply' },
    { value: 'mail-reply-all', label: 'Mail Reply All' },
    { value: 'male', label: 'Male' },
    { value: 'map', label: 'Map' },
    { value: 'map-marker', label: 'Map Marker' },
    { value: 'map-o', label: 'Map O' },
    { value: 'map-pin', label: 'Map Pin' },
    { value: 'map-signs', label: 'Map Signs' },
    { value: 'mars', label: 'Mars' },
    { value: 'mars-double', label: 'Mars Double' },
    { value: 'mars-stroke', label: 'Mars Stroke' },
    { value: 'mars-stroke-h', label: 'Mars Stroke H' },
    { value: 'mars-stroke-v', label: 'Mars Stroke V' },
    { value: 'maxcdn', label: 'Maxcdn' },
    { value: 'meanpath', label: 'Meanpath' },
    { value: 'medium', label: 'Medium' },
    { value: 'medkit', label: 'Medkit' },
    { value: 'meh-o', label: 'Meh O' },
    { value: 'mercury', label: 'Mercury' },
    { value: 'microphone', label: 'Microphone' },
    { value: 'microphone-slash', label: 'Microphone Slash' },
    { value: 'minus', label: 'Minus' },
    { value: 'minus-circle', label: 'Minus Circle' },
    { value: 'minus-square', label: 'Minus Square' },
    { value: 'minus-square-o', label: 'Minus Square O' },
    { value: 'mixcloud', label: 'Mixcloud' },
    { value: 'mobile', label: 'Mobile' },
    { value: 'mobile-phone', label: 'Mobile Phone' },
    { value: 'modx', label: 'Modx' },
    { value: 'money', label: 'Money' },
    { value: 'moon-o', label: 'Moon O' },
    { value: 'mortar-board', label: 'Mortar Board' },
    { value: 'motorcycle', label: 'Motorcycle' },
    { value: 'mouse-pointer', label: 'Mouse Pointer' },
    { value: 'music', label: 'Music' },
    { value: 'navicon', label: 'Navicon' },
    { value: 'neuter', label: 'Neuter' },
    { value: 'newspaper-o', label: 'Newspaper O' },
    { value: 'object-group', label: 'Object Group' },
    { value: 'object-ungroup', label: 'Object Ungroup' },
    { value: 'odnoklassniki', label: 'Odnoklassniki' },
    { value: 'odnoklassniki-square', label: 'Odnoklassniki Square' },
    { value: 'opencart', label: 'Opencart' },
    { value: 'openid', label: 'Openid' },
    { value: 'opera', label: 'Opera' },
    { value: 'optin-monster', label: 'Optin Monster' },
    { value: 'outdent', label: 'Outdent' },
    { value: 'pagelines', label: 'Pagelines' },
    { value: 'paint-brush', label: 'Paint Brush' },
    { value: 'paper-plane', label: 'Paper Plane' },
    { value: 'paper-plane-o', label: 'Paper Plane O' },
    { value: 'paperclip', label: 'Paperclip' },
    { value: 'paragraph', label: 'Paragraph' },
    { value: 'paste', label: 'Paste' },
    { value: 'pause', label: 'Pause' },
    { value: 'pause-circle', label: 'Pause Circle' },
    { value: 'pause-circle-o', label: 'Pause Circle O' },
    { value: 'paw', label: 'Paw' },
    { value: 'paypal', label: 'Paypal' },
    { value: 'pencil', label: 'Pencil' },
    { value: 'pencil-square', label: 'Pencil Square' },
    { value: 'pencil-square-o', label: 'Pencil Square O' },
    { value: 'percent', label: 'Percent' },
    { value: 'phone', label: 'Phone' },
    { value: 'phone-square', label: 'Phone Square' },
    { value: 'photo', label: 'Photo' },
    { value: 'picture-o', label: 'Picture O' },
    { value: 'pie-chart', label: 'Pie Chart' },
    { value: 'pied-piper', label: 'Pied Piper' },
    { value: 'pied-piper-alt', label: 'Pied Piper Alt' },
    { value: 'pinterest', label: 'Pinterest' },
    { value: 'pinterest-p', label: 'Pinterest P' },
    { value: 'pinterest-square', label: 'Pinterest Square' },
    { value: 'plane', label: 'Plane' },
    { value: 'play', label: 'Play' },
    { value: 'play-circle', label: 'Play Circle' },
    { value: 'play-circle-o', label: 'Play Circle O' },
    { value: 'plug', label: 'Plug' },
    { value: 'plus', label: 'Plus' },
    { value: 'plus-circle', label: 'Plus Circle' },
    { value: 'plus-square', label: 'Plus Square' },
    { value: 'plus-square-o', label: 'Plus Square O' },
    { value: 'power-off', label: 'Power Off' },
    { value: 'print', label: 'Print' },
    { value: 'product-hunt', label: 'Product Hunt' },
    { value: 'puzzle-piece', label: 'Puzzle Piece' },
    { value: 'qq', label: 'Qq' },
    { value: 'qrcode', label: 'Qrcode' },
    { value: 'question', label: 'Question' },
    { value: 'question-circle', label: 'Question Circle' },
    { value: 'quote-left', label: 'Quote Left' },
    { value: 'quote-right', label: 'Quote Right' },
    { value: 'ra', label: 'Ra' },
    { value: 'random', label: 'Random' },
    { value: 'rebel', label: 'Rebel' },
    { value: 'recycle', label: 'Recycle' },
    { value: 'reddit', label: 'Reddit' },
    { value: 'reddit-alien', label: 'Reddit Alien' },
    { value: 'reddit-square', label: 'Reddit Square' },
    { value: 'refresh', label: 'Refresh' },
    { value: 'registered', label: 'Registered' },
    { value: 'remove', label: 'Remove' },
    { value: 'renren', label: 'Renren' },
    { value: 'reorder', label: 'Reorder' },
    { value: 'repeat', label: 'Repeat' },
    { value: 'reply', label: 'Reply' },
    { value: 'reply-all', label: 'Reply All' },
    { value: 'retweet', label: 'Retweet' },
    { value: 'rmb', label: 'Rmb' },
    { value: 'road', label: 'Road' },
    { value: 'rocket', label: 'Rocket' },
    { value: 'rotate-left', label: 'Rotate Left' },
    { value: 'rotate-right', label: 'Rotate Right' },
    { value: 'rouble', label: 'Rouble' },
    { value: 'rss', label: 'Rss' },
    { value: 'rss-square', label: 'Rss Square' },
    { value: 'rub', label: 'Rub' },
    { value: 'ruble', label: 'Ruble' },
    { value: 'rupee', label: 'Rupee' },
    { value: 'safari', label: 'Safari' },
    { value: 'save', label: 'Save' },
    { value: 'scissors', label: 'Scissors' },
    { value: 'scribd', label: 'Scribd' },
    { value: 'search', label: 'Search' },
    { value: 'search-minus', label: 'Search Minus' },
    { value: 'search-plus', label: 'Search Plus' },
    { value: 'sellsy', label: 'Sellsy' },
    { value: 'send', label: 'Send' },
    { value: 'send-o', label: 'Send O' },
    { value: 'server', label: 'Server' },
    { value: 'share', label: 'Share' },
    { value: 'share-alt', label: 'Share Alt' },
    { value: 'share-alt-square', label: 'Share Alt Square' },
    { value: 'share-square', label: 'Share Square' },
    { value: 'share-square-o', label: 'Share Square O' },
    { value: 'shekel', label: 'Shekel' },
    { value: 'sheqel', label: 'Sheqel' },
    { value: 'shield', label: 'Shield' },
    { value: 'ship', label: 'Ship' },
    { value: 'shirtsinbulk', label: 'Shirtsinbulk' },
    { value: 'shopping-bag', label: 'Shopping Bag' },
    { value: 'shopping-basket', label: 'Shopping Basket' },
    { value: 'shopping-cart', label: 'Shopping Cart' },
    { value: 'sign-in', label: 'Sign In' },
    { value: 'sign-out', label: 'Sign Out' },
    { value: 'signal', label: 'Signal' },
    { value: 'simplybuilt', label: 'Simplybuilt' },
    { value: 'sitemap', label: 'Sitemap' },
    { value: 'skyatlas', label: 'Skyatlas' },
    { value: 'skype', label: 'Skype' },
    { value: 'slack', label: 'Slack' },
    { value: 'sliders', label: 'Sliders' },
    { value: 'slideshare', label: 'Slideshare' },
    { value: 'smile-o', label: 'Smile O' },
    { value: 'soccer-ball-o', label: 'Soccer Ball O' },
    { value: 'sort', label: 'Sort' },
    { value: 'sort-alpha-asc', label: 'Sort Alpha Asc' },
    { value: 'sort-alpha-desc', label: 'Sort Alpha Desc' },
    { value: 'sort-amount-asc', label: 'Sort Amount Asc' },
    { value: 'sort-amount-desc', label: 'Sort Amount Desc' },
    { value: 'sort-asc', label: 'Sort Asc' },
    { value: 'sort-desc', label: 'Sort Desc' },
    { value: 'sort-down', label: 'Sort Down' },
    { value: 'sort-numeric-asc', label: 'Sort Numeric Asc' },
    { value: 'sort-numeric-desc', label: 'Sort Numeric Desc' },
    { value: 'sort-up', label: 'Sort Up' },
    { value: 'soundcloud', label: 'Soundcloud' },
    { value: 'space-shuttle', label: 'Space Shuttle' },
    { value: 'spinner', label: 'Spinner' },
    { value: 'spoon', label: 'Spoon' },
    { value: 'spotify', label: 'Spotify' },
    { value: 'square', label: 'Square' },
    { value: 'square-o', label: 'Square O' },
    { value: 'stack-exchange', label: 'Stack Exchange' },
    { value: 'stack-overflow', label: 'Stack Overflow' },
    { value: 'star', label: 'Star' },
    { value: 'star-half', label: 'Star Half' },
    { value: 'star-half-empty', label: 'Star Half Empty' },
    { value: 'star-half-full', label: 'Star Half Full' },
    { value: 'star-half-o', label: 'Star Half O' },
    { value: 'star-o', label: 'Star O' },
    { value: 'steam', label: 'Steam' },
    { value: 'steam-square', label: 'Steam Square' },
    { value: 'step-backward', label: 'Step Backward' },
    { value: 'step-forward', label: 'Step Forward' },
    { value: 'stethoscope', label: 'Stethoscope' },
    { value: 'sticky-note', label: 'Sticky Note' },
    { value: 'sticky-note-o', label: 'Sticky Note O' },
    { value: 'stop', label: 'Stop' },
    { value: 'stop-circle', label: 'Stop Circle' },
    { value: 'stop-circle-o', label: 'Stop Circle O' },
    { value: 'street-view', label: 'Street View' },
    { value: 'strikethrough', label: 'Strikethrough' },
    { value: 'stumbleupon', label: 'Stumbleupon' },
    { value: 'stumbleupon-circle', label: 'Stumbleupon Circle' },
    { value: 'subscript', label: 'Subscript' },
    { value: 'subway', label: 'Subway' },
    { value: 'suitcase', label: 'Suitcase' },
    { value: 'sun-o', label: 'Sun O' },
    { value: 'superscript', label: 'Superscript' },
    { value: 'support', label: 'Support' },
    { value: 'table', label: 'Table' },
    { value: 'tablet', label: 'Tablet' },
    { value: 'tachometer', label: 'Tachometer' },
    { value: 'tag', label: 'Tag' },
    { value: 'tags', label: 'Tags' },
    { value: 'tasks', label: 'Tasks' },
    { value: 'taxi', label: 'Taxi' },
    { value: 'television', label: 'Television' },
    { value: 'tencent-weibo', label: 'Tencent Weibo' },
    { value: 'terminal', label: 'Terminal' },
    { value: 'text-height', label: 'Text Height' },
    { value: 'text-width', label: 'Text Width' },
    { value: 'th', label: 'Th' },
    { value: 'th-large', label: 'Th Large' },
    { value: 'th-list', label: 'Th List' },
    { value: 'thumb-tack', label: 'Thumb Tack' },
    { value: 'thumbs-down', label: 'Thumbs Down' },
    { value: 'thumbs-o-down', label: 'Thumbs O Down' },
    { value: 'thumbs-o-up', label: 'Thumbs O Up' },
    { value: 'thumbs-up', label: 'Thumbs Up' },
    { value: 'ticket', label: 'Ticket' },
    { value: 'times', label: 'Times' },
    { value: 'times-circle', label: 'Times Circle' },
    { value: 'times-circle-o', label: 'Times Circle O' },
    { value: 'tint', label: 'Tint' },
    { value: 'toggle-down', label: 'Toggle Down' },
    { value: 'toggle-left', label: 'Toggle Left' },
    { value: 'toggle-off', label: 'Toggle Off' },
    { value: 'toggle-on', label: 'Toggle On' },
    { value: 'toggle-right', label: 'Toggle Right' },
    { value: 'toggle-up', label: 'Toggle Up' },
    { value: 'trademark', label: 'Trademark' },
    { value: 'train', label: 'Train' },
    { value: 'transgender', label: 'Transgender' },
    { value: 'transgender-alt', label: 'Transgender Alt' },
    { value: 'trash', label: 'Trash' },
    { value: 'trash-o', label: 'Trash O' },
    { value: 'tree', label: 'Tree' },
    { value: 'trello', label: 'Trello' },
    { value: 'tripadvisor', label: 'Tripadvisor' },
    { value: 'trophy', label: 'Trophy' },
    { value: 'truck', label: 'Truck' },
    { value: 'try', label: 'Try' },
    { value: 'tty', label: 'Tty' },
    { value: 'tumblr', label: 'Tumblr' },
    { value: 'tumblr-square', label: 'Tumblr Square' },
    { value: 'turkish-lira', label: 'Turkish Lira' },
    { value: 'tv', label: 'Tv' },
    { value: 'twitch', label: 'Twitch' },
    { value: 'twitter', label: 'Twitter' },
    { value: 'twitter-square', label: 'Twitter Square' },
    { value: 'umbrella', label: 'Umbrella' },
    { value: 'underline', label: 'Underline' },
    { value: 'undo', label: 'Undo' },
    { value: 'university', label: 'University' },
    { value: 'unlink', label: 'Unlink' },
    { value: 'unlock', label: 'Unlock' },
    { value: 'unlock-alt', label: 'Unlock Alt' },
    { value: 'unsorted', label: 'Unsorted' },
    { value: 'upload', label: 'Upload' },
    { value: 'usb', label: 'Usb' },
    { value: 'usd', label: 'Usd' },
    { value: 'user', label: 'User' },
    { value: 'user-md', label: 'User Md' },
    { value: 'user-plus', label: 'User Plus' },
    { value: 'user-secret', label: 'User Secret' },
    { value: 'user-times', label: 'User Times' },
    { value: 'users', label: 'Users' },
    { value: 'venus', label: 'Venus' },
    { value: 'venus-double', label: 'Venus Double' },
    { value: 'venus-mars', label: 'Venus Mars' },
    { value: 'viacoin', label: 'Viacoin' },
    { value: 'video-camera', label: 'Video Camera' },
    { value: 'vimeo', label: 'Vimeo' },
    { value: 'vimeo-square', label: 'Vimeo Square' },
    { value: 'vine', label: 'Vine' },
    { value: 'vk', label: 'Vk' },
    { value: 'volume-down', label: 'Volume Down' },
    { value: 'volume-off', label: 'Volume Off' },
    { value: 'volume-up', label: 'Volume Up' },
    { value: 'warning', label: 'Warning' },
    { value: 'wechat', label: 'Wechat' },
    { value: 'weibo', label: 'Weibo' },
    { value: 'weixin', label: 'Weixin' },
    { value: 'whatsapp', label: 'Whatsapp' },
    { value: 'wheelchair', label: 'Wheelchair' },
    { value: 'wifi', label: 'Wifi' },
    { value: 'wikipedia-w', label: 'Wikipedia W' },
    { value: 'windows', label: 'Windows' },
    { value: 'won', label: 'Won' },
    { value: 'wordpress', label: 'Wordpress' },
    { value: 'wrench', label: 'Wrench' },
    { value: 'xing', label: 'Xing' },
    { value: 'xing-square', label: 'Xing Square' },
    { value: 'y-combinator', label: 'Y Combinator' },
    { value: 'y-combinator-square', label: 'Y Combinator Square' },
    { value: 'yahoo', label: 'Yahoo' },
    { value: 'yc', label: 'Yc' },
    { value: 'yc-square', label: 'Yc Square' },
    { value: 'yelp', label: 'Yelp' },
    { value: 'yen', label: 'Yen' },
    { value: 'youtube', label: 'Youtube' },
    { value: 'youtube-play', label: 'Youtube Play' },
    { value: 'youtube-square', label: 'Youtube Square' }
  ];
}
